version: "3" 

services:
  app:
    build: .
    command: npm start
    ports:
      - "4200:4200"
    volumes:
      - .:/web

  api-python:
    build: .
    command: python app.py
    ports:
      - "9000:9000"
    volumes:
      - .:/api
    environment:
      DATABASE_URL: postgres://docker-training@postgres/postgres

  postgres: 
    image: postgres:9.6.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker-training
    ports:
      - "5432:5432"
    volumes:
      - .:/postgres