version: "3" 

services:
  app:
    build: .
    ports:
      - "4200:4200"

  api-python:
    build: ../api-python
    ports:
      - "9000:9000"

  postgres: 
    image: postgres:9.6.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker-training
    ports:
      - "5432:5432"
    volumes:
      - .:/postgres